PeliculasWeeb/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using PeliculasWeb.Models;
using PeliculasWeb.Repository.IRepository;
using PeliculasWeb.Utils;

namespace PeliculasWeb.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly ICategoriaRepository _categoriaRepository;
        public CategoriasController(ICategoriaRepository categoriaRepository)
        {
            _categoriaRepository = categoriaRepository;
        }
        public IActionResult Index()
        {
            return View(new Categoria() { });
        }
        [HttpGet]
        public async Task<IActionResult> GetAllCategorias()
        {
            return Json(new {data = await _categoriaRepository.GetAllAsync(CT.RutaCategoriasApi) });
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Categoria categoria)
        {
            if (ModelState.IsValid) 
            {
                var data = await _categoriaRepository.AddAsync(CT.RutaCategoriasApi,categoria,HttpContext.Session.GetString("JWToken"));
                if (data is false)
                {
                    TempData["alertDanger"] = "Usuario no autorizado para crear una categoría";
                    
                }
                if (data is true)
                {
                    TempData["alertSuccess"] = "Categoria creada con éxito !";
                    
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            Categoria categoria = new();
            if (Id == null) 
            {
                return NotFound();
            }
            categoria = await _categoriaRepository.GetByIdAsync(CT.RutaCategoriasApi,Id.GetValueOrDefault());
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var data = await _categoriaRepository.UpdateAsync(CT.RutaCategoriasApi + categoria.Id, categoria, HttpContext.Session.GetString("JWToken"));
                if (data is false)
                {
                    TempData["alertDanger"] = "Usuario no autorizado para editar una categoría";
                }
                if (data is true)
                {
                    TempData["alertSuccess"] = "Categoría actualizada con éxito !";
                }

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int Id)
        {
            var status = await _categoriaRepository.DeleteAsync(CT.RutaCategoriasApi,Id, HttpContext.Session.GetString("JWToken"));

            if (status is true)
                return Json(new { succes = true,message = "Borrado Correctamente",});
            return Json(new { succes = true, message = "Error al borrar" });
        }

    }
}

PeliculasWeeb/Controllers/PeliculasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PeliculasWeb.Domain.DTOs;
using PeliculasWeb.Models;
using PeliculasWeb.Models.ViewModels;
using PeliculasWeb.Repository.IRepository;
using PeliculasWeb.Utils;
using System.IO;

namespace PeliculasWeb.Controllers
{
    public class PeliculasController : Controller
    {

        private readonly IPeliculaRepository _repository;
        private readonly ICategoriaRepository _repositoryCategoria;
        public PeliculasController(IPeliculaRepository repository, ICategoriaRepository repositoryCategoria)
        {
            _repository = repository;
            _repositoryCategoria = repositoryCategoria;
        }

        [HttpGet]
        public IActionResult Index() 
        {
            return View(new Pelicula() { });
        }

        [HttpGet]
        public async Task<IActionResult> GetAllPeliculas()
        {
            return Json(new {data = await _repository.GetAllAsync(CT.RutaPeliculasApi) });
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            IEnumerable<Categoria> npList = await _repositoryCategoria.GetAllAsync(CT.RutaCategoriasApi);
            PeliculasVM objVM = new()
            {
                ListaCategorias = npList.Select(x => new SelectListItem{
                   Text = x.Nombre,
                   Value = x.Id.ToString()
                }),

                Pelicula = new Pelicula()

            };

            return View(objVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PeliculaDTO pelicula)
        {
            var memoryStream = new MemoryStream();
            
            pelicula.RutaImagen.CopyTo(memoryStream);
            var imagenPelicula = memoryStream.ToArray();

            Pelicula peliculaEntity = new()
            {
                Id = pelicula.Id,
                CategoriaId = pelicula.CategoriaId,
                Clasificacion = pelicula.Clasificacion,
                Descripcion = pelicula.Descripcion,
                Duracion = pelicula.Duracion,
                FechaCreacion = pelicula.FechaCreacion,
                Nombre = pelicula.Nombre,
                RutaImagen = Convert.ToBase64String(imagenPelicula),
            };

            IEnumerable<Categoria> npList = await _repositoryCategoria.GetAllAsync(CT.RutaCategoriasApi);
            PeliculasVM objVM = new()
            {
                ListaCategorias = npList.Select(x => new SelectListItem
                {
                    Text = x.Nombre,
                    Value = x.Id.ToString()
                }),

                Pelicula = new Pelicula()

            };

            
            var data = await _repository.AddAsync(CT.RutaPeliculasApi, peliculaEntity, HttpContext.Session.GetString("JWToken"));
            if (data is false)
            {
                TempData["alertDanger"] = "Usuario no autorizado para crear una pelicula";
            }
            if (data is true)
            {
                TempData["alertSuccess"] = "Pelicula creada con éxito !";
            }
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            IEnumerable<Categoria> npList = await _repositoryCategoria.GetAllAsync(CT.RutaCategoriasApi);
            PeliculasEditVM objVM = new()
            {
                ListaCategorias = npList.Select(x => new SelectListItem
                {
                    Text = x.Nombre,
                    Value = x.Id.ToString()
                }),

                Pelicula = new PeliculasEditDTO()

            };

            if (Id==null)
            {
                return NotFound();
            }
            //Para mostrar los datos
            Pelicula peliculaResponse = new();
            peliculaResponse = await _repository.GetByIdAsync(CT.RutaPeliculasApi, Id.GetValueOrDefault());

            //var peliculaArrayBytes = Convert.FromBase64String(peliculaResponse.RutaImagen);
            //string outputPath = "C:\\Users\\KUBIT\\Desktop\\imagenPrueba.jpg";

            //;

            objVM.Pelicula = new PeliculasEditDTO()
            {
                Id = peliculaResponse.Id,
                CategoriaId = peliculaResponse.CategoriaId,
                Clasificacion = peliculaResponse.Clasificacion,
                Descripcion = peliculaResponse.Descripcion,
                Duracion = peliculaResponse.Duracion,
                FechaCreacion = peliculaResponse.FechaCreacion,
                Nombre = peliculaResponse.Nombre,
                RutaImagen = peliculaResponse.RutaImagen
            };

            if (objVM.Pelicula == null)
            {
                return NotFound();
            }

            return View(objVM);

        }
        [HttpPost]
        public async Task<IActionResult> Update(PeliculaDTO pelicula)
        {
            byte[] imagenPelicula = { };

            if (pelicula.RutaImagen is not null)
            {
                var memoryStream = new MemoryStream();

                pelicula.RutaImagen.CopyTo(memoryStream);
                imagenPelicula = memoryStream.ToArray();
            }
            

            Pelicula peliculaEntity = new()
            {
                Id = pelicula.Id,
                CategoriaId = pelicula.CategoriaId,
                Clasificacion = pelicula.Clasificacion,
                Descripcion = pelicula.Descripcion,
                Duracion = pelicula.Duracion,
                FechaCreacion = pelicula.FechaCreacion,
                Nombre = pelicula.Nombre,
                RutaImagen = Convert.ToBase64String(imagenPelicula),
            };

            IEnumerable<Categoria> npList = await _repositoryCategoria.GetAllAsync(CT.RutaCategoriasApi);
            PeliculasVM objVM = new()
            {
                ListaCategorias = npList.Select(x => new SelectListItem
                {
                    Text = x.Nombre,
                    Value = x.Id.ToString()
                }),

                Pelicula = peliculaEntity

            };

            var data = await _repository.UpdateAsync(CT.RutaPeliculasApi + pelicula.Id, peliculaEntity, HttpContext.Session.GetString("JWToken"));
            if (data is false)
            {
                TempData["alertDanger"] = "Usuario no autorizado para editar una pelicula";
            }
            else if (data is true)
            {
                TempData["alertSuccess"] = "Pelicula editada con exito";
            }

            return RedirectToAction(nameof(Index));

        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int Id)
        {
            var status = await _repository.DeleteAsync(CT.RutaPeliculasApi, Id, HttpContext.Session.GetString("JWToken"));

            if (status is true)
                return Json(new { succes = true, message = "Borrado Correctamente" });

            return Json(new { succes = true, message = "Error al borrar" });
        }
        [HttpGet]
        public async Task<IActionResult> GetPeliculasEnCategoria(int id)
        {
            return Json(new { data = await _repository.GetPeliculasEnCategoriasAsync(CT.RutaPeliculasEnCategoriasApi, id) });
        }
    }
}

PeliculasWeeb/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using PeliculasWeb.Models;
using PeliculasWeb.Repository.IRepository;
using PeliculasWeb.Utils;

namespace PeliculasWeb.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        public UsuariosController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }
        public IActionResult Index()
        {
            return View(new UsuarioU() { });
        }
        [HttpGet]
        public async Task<IActionResult> GetAllUsuarios()
        {
            return Json(new {data = await _usuarioRepository.GetAllAsync(CT.RutaUsuariosApi) });
        }

    }
}

PeliculasWeeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpAcc
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeliculasWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeliculasWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeliculasWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Peliculas" asp-action="Index">Peliculas</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (httpAcc.HttpContext.Session.GetString("JWToken") != null && httpAcc.HttpContext.Session.GetString("JWToken").ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Salir</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Acceder</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Registro">Registro</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="jumbotron jumbotron-fluid">
        <div class="container-fluid">
            <img class="img-fluid" src="~/imagenes/banner-peliculas-api.jpg"  />
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PeliculasWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>